### ISSUE TITLE
Tests fail on invisible line break

### ISSUE THREAD

**Issue by dotherightthing** [dotherightthing/markdown-it-gallery-section#4]
```sh
         line 16:

      AssertionError: expected '<ContentSection class="" headingContent="Itchy feet"><Gallery class="" id="0" :images="[{alt:\'Image description.\',caption:\'Image caption.\',extraAttributes:{},id:0,src:\'/images/tourdiaries/east-asia/china-1/01/image.jpg\'}]"><h2>Itchy feet</h2>\n</Gallery><div class="entry-content"></p>\n<p>Section text.</p>\n</div></ContentSection>' to equal '<ContentSection class="" headingContent="Itchy feet"><Gallery class="" id="0" :images="[{alt:\'Image description.\',caption:\'Image caption.\',extraAttributes:{},id:0,src:\'/images/tourdiaries/east-asia/china-1/01/image.jpg\'}]"><h2>Itchy feet</h2>\n</Gallery><div class="entry-content"></p>\n\n<p>Section text.</p>\n</div></ContentSection>\n'
      + expected - actual

       <ContentSection class="" headingContent="Itchy feet"><Gallery class="" id="0" :images="[{alt:'Image description.',caption:'Image caption.',extraAttributes:{},id:0,src:'/images/tourdiaries/east-asia/china-1/01/image.jpg'}]"><h2>Itchy feet</h2>
       </Gallery><div class="entry-content"></p>
      +
       <p>Section text.</p>
      -</div></ContentSection>
      +</div></ContentSection>
      
      at Function.assert.strictEqual (node_modules/chai/lib/chai/interface/assert.js:169:32)
      at Context.<anonymous> (node_modules/markdown-it-testgen/index.js:196:26)
      at processImmediate (node:internal/timers:464:21)
```

**Comment by dotherightthing** [comment]
The test diff thinks that there is a line break after the fixture HTML. Perhaps this has something to do with the use of a custom HTML tag?

Added `stripTrailingLineBreakFromFixtureHtml` option to `generate` function:

```js
describe('tests', (assert) => {
  const md = require('markdown-it')()
    .use(require('../'), 'name');
    generate(
      path.join(__dirname, 'fixtures/tests.txt'),
      {
        stripTrailingLineBreakFromFixtureHtml: true
      },
      md
    );
});
```
